/**
 * @import { Table } from '../table.js';
 * @import { CompressionType_ } from '../types.js';
 * @import { Sink } from './sink.js';
 */
import { Column } from '../column.js';
import { Table as Table_ } from '../table.js';
import { tableToIPC } from './table-to-ipc.js';

/**
 * Encode multiple Arrow tables into a single Arrow IPC stream.
 *
 * Each input table contributes its record batches to the output stream in
 * order — the result is a multi-batch IPC stream that downstream readers
 * (PyArrow, arrow-js, flechette itself) consume in one pass. All input
 * tables MUST share an equivalent schema (same field count and names; the
 * first table's schema is used for the output).
 *
 * Equivalent to concatenating multiple single-table IPC streams except the
 * intermediate schema headers and EOS markers are stripped — naive
 * concatenation produces a stream with multiple EOS markers, which causes
 * readers to stop after the first table's batches.
 *
 * @param {Table[]} tables The Arrow tables to encode (must share a schema).
 * @param {object} [options] Encoding options.
 * @param {Sink} [options.sink] IPC byte consumer.
 * @param {'stream' | 'file'} [options.format] Arrow stream or file format.
 * @param {CompressionType_ | null} [options.codec] Compression codec to apply.
 * @returns {Uint8Array | null} The generated bytes (for an in-memory sink)
 *  or null (if using a sink that writes bytes elsewhere).
 */
export function tablesToIPC(tables, options) {
  if (!tables || tables.length === 0) {
    throw new Error('tablesToIPC requires at least one table');
  }
  if (tables.length === 1) {
    return tableToIPC(tables[0], options);
  }
  return tableToIPC(concatTables(tables), options);
}

// concatTables is exported below — `tablesToIPC` is just a thin wrapper that
// concatenates first then encodes.

/**
 * Concatenate multiple Tables (sharing a schema) row-wise into a single
 * Table whose Columns carry every input's batches in order. Existing batch
 * boundaries are preserved — if input table A has 2 batches and B has 3,
 * the result has 5 batches in `[A0, A1, B0, B1, B2]` order. (When you then
 * encode via `tablesToIPC` / `tableToIPC`, each batch becomes one IPC
 * record message, so the wire stream has 5 records.)
 *
 * The new Table reuses the first input's schema and per-column types.
 * Inputs must agree on field count and field names; type compatibility
 * beyond that is the caller's responsibility.
 *
 * @param {Table[]} tables The Arrow tables to concatenate.
 * @returns {Table} A new Table with batches drawn from every input in order.
 */
export function concatTables(tables) {
  if (!tables || tables.length === 0) {
    throw new Error('concatTables requires at least one table');
  }
  if (tables.length === 1) return tables[0];

  const head = tables[0];
  const headFields = head.schema.fields;

  // Validate schema compatibility before allocating.
  for (let i = 1; i < tables.length; i++) {
    const fields = tables[i].schema.fields;
    if (fields.length !== headFields.length) {
      throw new Error(
        `concatTables: table at index ${i} has ${fields.length} fields, ` +
        `expected ${headFields.length}`,
      );
    }
    for (let f = 0; f < headFields.length; f++) {
      if (fields[f].name !== headFields[f].name) {
        throw new Error(
          `concatTables: table at index ${i} field[${f}] name is ` +
          `'${fields[f].name}', expected '${headFields[f].name}'`,
        );
      }
    }
  }

  // For each column position, concatenate the per-table batches into a
  // single Column. The first table's column type is authoritative; other
  // tables' batches are appended assuming type-compatibility.
  const mergedChildren = headFields.map((_, colIdx) => {
    const headCol = head.children[colIdx];
    const allBatches = [];
    for (const t of tables) {
      const col = t.children[colIdx];
      for (const b of col.data) allBatches.push(b);
    }
    return new Column(allBatches, headCol.type);
  });

  return new Table_(head.schema, mergedChildren);
}
